nameOverride: ""
fullnameOverride: ""

image:
  container: chefbook-backend-encryption-service
  registry: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: [ ]

config:
  develop: false
  # Leave empty for stdout only
  logsPath: ""

  checkSubscription: true

  postgres:
    host: ""
    port: 5432
    dbName: chefbook-encryption

  rabbitmq:
    name: ""
    namespace: ""
    port: 5672
    vhost: ""

  smtp:
    host: smtp.gmail.com
    port: 465
    email: ""
    sendAttempts: 3

services:
  auth:
    name: chefbook-backend-auth-service
    namespace: ""
    port: 8080
  profile:
    name: chefbook-backend-profile-service
    namespace: ""
    port: 8080
  recipe:
    name: chefbook-backend-recipe-service
    namespace: ""
    port: 8080

secrets:
  postgres:
    name: postgres-secrets
    userRef: user
    passwordRef: password
  rabbitmq:
    name: rabbitmq-secrets
    userRef: user
    passwordRef: password
  smtp:
    name: smtp-secrets
    passwordRef: password

service:
  type: ClusterIP
  port: 8080

replicaCount: 2

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
