// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/create-encrypted-vault.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEncryptedVaultRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PublicKey           []byte                 `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	EncryptedPrivateKey []byte                 `protobuf:"bytes,3,opt,name=encryptedPrivateKey,proto3" json:"encryptedPrivateKey,omitempty"`
	Salt                []byte                 `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateEncryptedVaultRequest) Reset() {
	*x = CreateEncryptedVaultRequest{}
	mi := &file_v1_create_encrypted_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEncryptedVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncryptedVaultRequest) ProtoMessage() {}

func (x *CreateEncryptedVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_create_encrypted_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncryptedVaultRequest.ProtoReflect.Descriptor instead.
func (*CreateEncryptedVaultRequest) Descriptor() ([]byte, []int) {
	return file_v1_create_encrypted_vault_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEncryptedVaultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEncryptedVaultRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *CreateEncryptedVaultRequest) GetEncryptedPrivateKey() []byte {
	if x != nil {
		return x.EncryptedPrivateKey
	}
	return nil
}

func (x *CreateEncryptedVaultRequest) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type CreateEncryptedVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEncryptedVaultResponse) Reset() {
	*x = CreateEncryptedVaultResponse{}
	mi := &file_v1_create_encrypted_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEncryptedVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncryptedVaultResponse) ProtoMessage() {}

func (x *CreateEncryptedVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_create_encrypted_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncryptedVaultResponse.ProtoReflect.Descriptor instead.
func (*CreateEncryptedVaultResponse) Descriptor() ([]byte, []int) {
	return file_v1_create_encrypted_vault_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEncryptedVaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_create_encrypted_vault_proto protoreflect.FileDescriptor

const file_v1_create_encrypted_vault_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/create-encrypted-vault.proto\x12\x02v1\"\x99\x01\n" +
	"\x1bCreateEncryptedVaultRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\fR\tpublicKey\x120\n" +
	"\x13encryptedPrivateKey\x18\x03 \x01(\fR\x13encryptedPrivateKey\x12\x12\n" +
	"\x04salt\x18\x04 \x01(\fR\x04salt\"8\n" +
	"\x1cCreateEncryptedVaultResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_create_encrypted_vault_proto_rawDescOnce sync.Once
	file_v1_create_encrypted_vault_proto_rawDescData []byte
)

func file_v1_create_encrypted_vault_proto_rawDescGZIP() []byte {
	file_v1_create_encrypted_vault_proto_rawDescOnce.Do(func() {
		file_v1_create_encrypted_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_create_encrypted_vault_proto_rawDesc), len(file_v1_create_encrypted_vault_proto_rawDesc)))
	})
	return file_v1_create_encrypted_vault_proto_rawDescData
}

var file_v1_create_encrypted_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_create_encrypted_vault_proto_goTypes = []any{
	(*CreateEncryptedVaultRequest)(nil),  // 0: v1.CreateEncryptedVaultRequest
	(*CreateEncryptedVaultResponse)(nil), // 1: v1.CreateEncryptedVaultResponse
}
var file_v1_create_encrypted_vault_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_create_encrypted_vault_proto_init() }
func file_v1_create_encrypted_vault_proto_init() {
	if File_v1_create_encrypted_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_create_encrypted_vault_proto_rawDesc), len(file_v1_create_encrypted_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_create_encrypted_vault_proto_goTypes,
		DependencyIndexes: file_v1_create_encrypted_vault_proto_depIdxs,
		MessageInfos:      file_v1_create_encrypted_vault_proto_msgTypes,
	}.Build()
	File_v1_create_encrypted_vault_proto = out.File
	file_v1_create_encrypted_vault_proto_goTypes = nil
	file_v1_create_encrypted_vault_proto_depIdxs = nil
}
