// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/delete-encrypted-vault.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteEncryptedVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	DeleteCode    string                 `protobuf:"bytes,2,opt,name=deleteCode,proto3" json:"deleteCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEncryptedVaultRequest) Reset() {
	*x = DeleteEncryptedVaultRequest{}
	mi := &file_v1_delete_encrypted_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEncryptedVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEncryptedVaultRequest) ProtoMessage() {}

func (x *DeleteEncryptedVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_encrypted_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEncryptedVaultRequest.ProtoReflect.Descriptor instead.
func (*DeleteEncryptedVaultRequest) Descriptor() ([]byte, []int) {
	return file_v1_delete_encrypted_vault_proto_rawDescGZIP(), []int{0}
}

func (x *DeleteEncryptedVaultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteEncryptedVaultRequest) GetDeleteCode() string {
	if x != nil {
		return x.DeleteCode
	}
	return ""
}

type DeleteEncryptedVaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEncryptedVaultResponse) Reset() {
	*x = DeleteEncryptedVaultResponse{}
	mi := &file_v1_delete_encrypted_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEncryptedVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEncryptedVaultResponse) ProtoMessage() {}

func (x *DeleteEncryptedVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_delete_encrypted_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEncryptedVaultResponse.ProtoReflect.Descriptor instead.
func (*DeleteEncryptedVaultResponse) Descriptor() ([]byte, []int) {
	return file_v1_delete_encrypted_vault_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteEncryptedVaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_delete_encrypted_vault_proto protoreflect.FileDescriptor

const file_v1_delete_encrypted_vault_proto_rawDesc = "" +
	"\n" +
	"\x1fv1/delete-encrypted-vault.proto\x12\x02v1\"U\n" +
	"\x1bDeleteEncryptedVaultRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1e\n" +
	"\n" +
	"deleteCode\x18\x02 \x01(\tR\n" +
	"deleteCode\"8\n" +
	"\x1cDeleteEncryptedVaultResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_delete_encrypted_vault_proto_rawDescOnce sync.Once
	file_v1_delete_encrypted_vault_proto_rawDescData []byte
)

func file_v1_delete_encrypted_vault_proto_rawDescGZIP() []byte {
	file_v1_delete_encrypted_vault_proto_rawDescOnce.Do(func() {
		file_v1_delete_encrypted_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_delete_encrypted_vault_proto_rawDesc), len(file_v1_delete_encrypted_vault_proto_rawDesc)))
	})
	return file_v1_delete_encrypted_vault_proto_rawDescData
}

var file_v1_delete_encrypted_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_delete_encrypted_vault_proto_goTypes = []any{
	(*DeleteEncryptedVaultRequest)(nil),  // 0: v1.DeleteEncryptedVaultRequest
	(*DeleteEncryptedVaultResponse)(nil), // 1: v1.DeleteEncryptedVaultResponse
}
var file_v1_delete_encrypted_vault_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_delete_encrypted_vault_proto_init() }
func file_v1_delete_encrypted_vault_proto_init() {
	if File_v1_delete_encrypted_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_delete_encrypted_vault_proto_rawDesc), len(file_v1_delete_encrypted_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_delete_encrypted_vault_proto_goTypes,
		DependencyIndexes: file_v1_delete_encrypted_vault_proto_depIdxs,
		MessageInfos:      file_v1_delete_encrypted_vault_proto_msgTypes,
	}.Build()
	File_v1_delete_encrypted_vault_proto = out.File
	file_v1_delete_encrypted_vault_proto_goTypes = nil
	file_v1_delete_encrypted_vault_proto_depIdxs = nil
}
