// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/encryption-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_encryption_service_proto protoreflect.FileDescriptor

const file_v1_encryption_service_proto_rawDesc = "" +
	"\n" +
	"\x1bv1/encryption-service.proto\x12\x02v1\x1a\x1cv1/has-encrypted-vault.proto\x1a v1/get-encrypted-vault-key.proto\x1a\x1fv1/create-encrypted-vault.proto\x1a)v1/request-encrypted-vault-deletion.proto\x1a\x1fv1/delete-encrypted-vault.proto\x1a v1/get-recipe-key-requests.proto\x1a\"v1/request-recipe-key-access.proto\x1a\x17v1/get-recipe-key.proto\x1a\x17v1/set-recipe-key.proto\x1a\x1av1/delete-recipe-key.proto2\xfa\x06\n" +
	"\x11EncryptionService\x12P\n" +
	"\x11HasEncryptedVault\x12\x1c.v1.HasEncryptedVaultRequest\x1a\x1d.v1.HasEncryptedVaultResponse\x12Y\n" +
	"\x14GetEncryptedVaultKey\x12\x1f.v1.GetEncryptedVaultKeyRequest\x1a .v1.GetEncryptedVaultKeyResponse\x12Y\n" +
	"\x14CreateEncryptedVault\x12\x1f.v1.CreateEncryptedVaultRequest\x1a .v1.CreateEncryptedVaultResponse\x12t\n" +
	"\x1dRequestEncryptedVaultDeletion\x12(.v1.RequestEncryptedVaultDeletionRequest\x1a).v1.RequestEncryptedVaultDeletionResponse\x12Y\n" +
	"\x14DeleteEncryptedVault\x12\x1f.v1.DeleteEncryptedVaultRequest\x1a .v1.DeleteEncryptedVaultResponse\x12Y\n" +
	"\x14GetRecipeKeyRequests\x12\x1f.v1.GetRecipeKeyRequestsRequest\x1a .v1.GetRecipeKeyRequestsResponse\x12_\n" +
	"\x16RequestRecipeKeyAccess\x12!.v1.RequestRecipeKeyAccessRequest\x1a\".v1.RequestRecipeKeyAccessResponse\x12A\n" +
	"\fGetRecipeKey\x12\x17.v1.GetRecipeKeyRequest\x1a\x18.v1.GetRecipeKeyResponse\x12A\n" +
	"\fSetRecipeKey\x12\x17.v1.SetRecipeKeyRequest\x1a\x18.v1.SetRecipeKeyResponse\x12J\n" +
	"\x0fDeleteRecipeKey\x12\x1a.v1.DeleteRecipeKeyRequest\x1a\x1b.v1.DeleteRecipeKeyResponseBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var file_v1_encryption_service_proto_goTypes = []any{
	(*HasEncryptedVaultRequest)(nil),              // 0: v1.HasEncryptedVaultRequest
	(*GetEncryptedVaultKeyRequest)(nil),           // 1: v1.GetEncryptedVaultKeyRequest
	(*CreateEncryptedVaultRequest)(nil),           // 2: v1.CreateEncryptedVaultRequest
	(*RequestEncryptedVaultDeletionRequest)(nil),  // 3: v1.RequestEncryptedVaultDeletionRequest
	(*DeleteEncryptedVaultRequest)(nil),           // 4: v1.DeleteEncryptedVaultRequest
	(*GetRecipeKeyRequestsRequest)(nil),           // 5: v1.GetRecipeKeyRequestsRequest
	(*RequestRecipeKeyAccessRequest)(nil),         // 6: v1.RequestRecipeKeyAccessRequest
	(*GetRecipeKeyRequest)(nil),                   // 7: v1.GetRecipeKeyRequest
	(*SetRecipeKeyRequest)(nil),                   // 8: v1.SetRecipeKeyRequest
	(*DeleteRecipeKeyRequest)(nil),                // 9: v1.DeleteRecipeKeyRequest
	(*HasEncryptedVaultResponse)(nil),             // 10: v1.HasEncryptedVaultResponse
	(*GetEncryptedVaultKeyResponse)(nil),          // 11: v1.GetEncryptedVaultKeyResponse
	(*CreateEncryptedVaultResponse)(nil),          // 12: v1.CreateEncryptedVaultResponse
	(*RequestEncryptedVaultDeletionResponse)(nil), // 13: v1.RequestEncryptedVaultDeletionResponse
	(*DeleteEncryptedVaultResponse)(nil),          // 14: v1.DeleteEncryptedVaultResponse
	(*GetRecipeKeyRequestsResponse)(nil),          // 15: v1.GetRecipeKeyRequestsResponse
	(*RequestRecipeKeyAccessResponse)(nil),        // 16: v1.RequestRecipeKeyAccessResponse
	(*GetRecipeKeyResponse)(nil),                  // 17: v1.GetRecipeKeyResponse
	(*SetRecipeKeyResponse)(nil),                  // 18: v1.SetRecipeKeyResponse
	(*DeleteRecipeKeyResponse)(nil),               // 19: v1.DeleteRecipeKeyResponse
}
var file_v1_encryption_service_proto_depIdxs = []int32{
	0,  // 0: v1.EncryptionService.HasEncryptedVault:input_type -> v1.HasEncryptedVaultRequest
	1,  // 1: v1.EncryptionService.GetEncryptedVaultKey:input_type -> v1.GetEncryptedVaultKeyRequest
	2,  // 2: v1.EncryptionService.CreateEncryptedVault:input_type -> v1.CreateEncryptedVaultRequest
	3,  // 3: v1.EncryptionService.RequestEncryptedVaultDeletion:input_type -> v1.RequestEncryptedVaultDeletionRequest
	4,  // 4: v1.EncryptionService.DeleteEncryptedVault:input_type -> v1.DeleteEncryptedVaultRequest
	5,  // 5: v1.EncryptionService.GetRecipeKeyRequests:input_type -> v1.GetRecipeKeyRequestsRequest
	6,  // 6: v1.EncryptionService.RequestRecipeKeyAccess:input_type -> v1.RequestRecipeKeyAccessRequest
	7,  // 7: v1.EncryptionService.GetRecipeKey:input_type -> v1.GetRecipeKeyRequest
	8,  // 8: v1.EncryptionService.SetRecipeKey:input_type -> v1.SetRecipeKeyRequest
	9,  // 9: v1.EncryptionService.DeleteRecipeKey:input_type -> v1.DeleteRecipeKeyRequest
	10, // 10: v1.EncryptionService.HasEncryptedVault:output_type -> v1.HasEncryptedVaultResponse
	11, // 11: v1.EncryptionService.GetEncryptedVaultKey:output_type -> v1.GetEncryptedVaultKeyResponse
	12, // 12: v1.EncryptionService.CreateEncryptedVault:output_type -> v1.CreateEncryptedVaultResponse
	13, // 13: v1.EncryptionService.RequestEncryptedVaultDeletion:output_type -> v1.RequestEncryptedVaultDeletionResponse
	14, // 14: v1.EncryptionService.DeleteEncryptedVault:output_type -> v1.DeleteEncryptedVaultResponse
	15, // 15: v1.EncryptionService.GetRecipeKeyRequests:output_type -> v1.GetRecipeKeyRequestsResponse
	16, // 16: v1.EncryptionService.RequestRecipeKeyAccess:output_type -> v1.RequestRecipeKeyAccessResponse
	17, // 17: v1.EncryptionService.GetRecipeKey:output_type -> v1.GetRecipeKeyResponse
	18, // 18: v1.EncryptionService.SetRecipeKey:output_type -> v1.SetRecipeKeyResponse
	19, // 19: v1.EncryptionService.DeleteRecipeKey:output_type -> v1.DeleteRecipeKeyResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_encryption_service_proto_init() }
func file_v1_encryption_service_proto_init() {
	if File_v1_encryption_service_proto != nil {
		return
	}
	file_v1_has_encrypted_vault_proto_init()
	file_v1_get_encrypted_vault_key_proto_init()
	file_v1_create_encrypted_vault_proto_init()
	file_v1_request_encrypted_vault_deletion_proto_init()
	file_v1_delete_encrypted_vault_proto_init()
	file_v1_get_recipe_key_requests_proto_init()
	file_v1_request_recipe_key_access_proto_init()
	file_v1_get_recipe_key_proto_init()
	file_v1_set_recipe_key_proto_init()
	file_v1_delete_recipe_key_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_encryption_service_proto_rawDesc), len(file_v1_encryption_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_encryption_service_proto_goTypes,
		DependencyIndexes: file_v1_encryption_service_proto_depIdxs,
	}.Build()
	File_v1_encryption_service_proto = out.File
	file_v1_encryption_service_proto_goTypes = nil
	file_v1_encryption_service_proto_depIdxs = nil
}
