// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/get-recipe-key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecipeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeKeyRequest) Reset() {
	*x = GetRecipeKeyRequest{}
	mi := &file_v1_get_recipe_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyRequest) ProtoMessage() {}

func (x *GetRecipeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecipeKeyRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *GetRecipeKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRecipeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncryptedKey  []byte                 `protobuf:"bytes,1,opt,name=encryptedKey,proto3,oneof" json:"encryptedKey,omitempty"`
	Iv            []byte                 `protobuf:"bytes,2,opt,name=iv,proto3,oneof" json:"iv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeKeyResponse) Reset() {
	*x = GetRecipeKeyResponse{}
	mi := &file_v1_get_recipe_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyResponse) ProtoMessage() {}

func (x *GetRecipeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecipeKeyResponse) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *GetRecipeKeyResponse) GetIv() []byte {
	if x != nil {
		return x.Iv
	}
	return nil
}

var File_v1_get_recipe_key_proto protoreflect.FileDescriptor

const file_v1_get_recipe_key_proto_rawDesc = "" +
	"\n" +
	"\x17v1/get-recipe-key.proto\x12\x02v1\"I\n" +
	"\x13GetRecipeKeyRequest\x12\x1a\n" +
	"\brecipeId\x18\x01 \x01(\tR\brecipeId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"l\n" +
	"\x14GetRecipeKeyResponse\x12'\n" +
	"\fencryptedKey\x18\x01 \x01(\fH\x00R\fencryptedKey\x88\x01\x01\x12\x13\n" +
	"\x02iv\x18\x02 \x01(\fH\x01R\x02iv\x88\x01\x01B\x0f\n" +
	"\r_encryptedKeyB\x05\n" +
	"\x03_ivBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_get_recipe_key_proto_rawDescOnce sync.Once
	file_v1_get_recipe_key_proto_rawDescData []byte
)

func file_v1_get_recipe_key_proto_rawDescGZIP() []byte {
	file_v1_get_recipe_key_proto_rawDescOnce.Do(func() {
		file_v1_get_recipe_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_recipe_key_proto_rawDesc), len(file_v1_get_recipe_key_proto_rawDesc)))
	})
	return file_v1_get_recipe_key_proto_rawDescData
}

var file_v1_get_recipe_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_get_recipe_key_proto_goTypes = []any{
	(*GetRecipeKeyRequest)(nil),  // 0: v1.GetRecipeKeyRequest
	(*GetRecipeKeyResponse)(nil), // 1: v1.GetRecipeKeyResponse
}
var file_v1_get_recipe_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_get_recipe_key_proto_init() }
func file_v1_get_recipe_key_proto_init() {
	if File_v1_get_recipe_key_proto != nil {
		return
	}
	file_v1_get_recipe_key_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_recipe_key_proto_rawDesc), len(file_v1_get_recipe_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_recipe_key_proto_goTypes,
		DependencyIndexes: file_v1_get_recipe_key_proto_depIdxs,
		MessageInfos:      file_v1_get_recipe_key_proto_msgTypes,
	}.Build()
	File_v1_get_recipe_key_proto = out.File
	file_v1_get_recipe_key_proto_goTypes = nil
	file_v1_get_recipe_key_proto_depIdxs = nil
}
