// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: v1/get-recipe-key-requests.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecipeKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName   *string `protobuf:"bytes,2,opt,name=userName,proto3,oneof" json:"userName,omitempty"`
	UserAvatar *string `protobuf:"bytes,3,opt,name=userAvatar,proto3,oneof" json:"userAvatar,omitempty"`
	Status     string  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PublicKey  []byte  `protobuf:"bytes,5,opt,name=publicKey,proto3,oneof" json:"publicKey,omitempty"`
}

func (x *RecipeKeyRequest) Reset() {
	*x = RecipeKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_get_recipe_key_requests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecipeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeKeyRequest) ProtoMessage() {}

func (x *RecipeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeKeyRequest.ProtoReflect.Descriptor instead.
func (*RecipeKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{0}
}

func (x *RecipeKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecipeKeyRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *RecipeKeyRequest) GetUserAvatar() string {
	if x != nil && x.UserAvatar != nil {
		return *x.UserAvatar
	}
	return ""
}

func (x *RecipeKeyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecipeKeyRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetRecipeKeyRequestsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipeId string `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetRecipeKeyRequestsRequest) Reset() {
	*x = GetRecipeKeyRequestsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_get_recipe_key_requests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecipeKeyRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyRequestsRequest) ProtoMessage() {}

func (x *GetRecipeKeyRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyRequestsRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecipeKeyRequestsRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *GetRecipeKeyRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRecipeKeyRequestsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests []*RecipeKeyRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
}

func (x *GetRecipeKeyRequestsResponse) Reset() {
	*x = GetRecipeKeyRequestsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_get_recipe_key_requests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecipeKeyRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyRequestsResponse) ProtoMessage() {}

func (x *GetRecipeKeyRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyRequestsResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecipeKeyRequestsResponse) GetRequests() []*RecipeKeyRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_v1_get_recipe_key_requests_proto protoreflect.FileDescriptor

var file_v1_get_recipe_key_requests_proto_rawDesc = []byte{
	0x0a, 0x20, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x74, 0x2d, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2d,
	0x6b, 0x65, 0x79, 0x2d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0xd5, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x21, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x02, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x51,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x50, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x65, 0x70, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x6c, 0x69, 0x65, 0x2f, 0x63, 0x68,
	0x65, 0x66, 0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_get_recipe_key_requests_proto_rawDescOnce sync.Once
	file_v1_get_recipe_key_requests_proto_rawDescData = file_v1_get_recipe_key_requests_proto_rawDesc
)

func file_v1_get_recipe_key_requests_proto_rawDescGZIP() []byte {
	file_v1_get_recipe_key_requests_proto_rawDescOnce.Do(func() {
		file_v1_get_recipe_key_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_get_recipe_key_requests_proto_rawDescData)
	})
	return file_v1_get_recipe_key_requests_proto_rawDescData
}

var file_v1_get_recipe_key_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_get_recipe_key_requests_proto_goTypes = []interface{}{
	(*RecipeKeyRequest)(nil),             // 0: v1.RecipeKeyRequest
	(*GetRecipeKeyRequestsRequest)(nil),  // 1: v1.GetRecipeKeyRequestsRequest
	(*GetRecipeKeyRequestsResponse)(nil), // 2: v1.GetRecipeKeyRequestsResponse
}
var file_v1_get_recipe_key_requests_proto_depIdxs = []int32{
	0, // 0: v1.GetRecipeKeyRequestsResponse.requests:type_name -> v1.RecipeKeyRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_get_recipe_key_requests_proto_init() }
func file_v1_get_recipe_key_requests_proto_init() {
	if File_v1_get_recipe_key_requests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_get_recipe_key_requests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecipeKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_get_recipe_key_requests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecipeKeyRequestsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_get_recipe_key_requests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecipeKeyRequestsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_get_recipe_key_requests_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_get_recipe_key_requests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_recipe_key_requests_proto_goTypes,
		DependencyIndexes: file_v1_get_recipe_key_requests_proto_depIdxs,
		MessageInfos:      file_v1_get_recipe_key_requests_proto_msgTypes,
	}.Build()
	File_v1_get_recipe_key_requests_proto = out.File
	file_v1_get_recipe_key_requests_proto_rawDesc = nil
	file_v1_get_recipe_key_requests_proto_goTypes = nil
	file_v1_get_recipe_key_requests_proto_depIdxs = nil
}
