// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/get-recipe-key-requests.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecipeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName      *string                `protobuf:"bytes,2,opt,name=userName,proto3,oneof" json:"userName,omitempty"`
	UserAvatar    *string                `protobuf:"bytes,3,opt,name=userAvatar,proto3,oneof" json:"userAvatar,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,5,opt,name=publicKey,proto3,oneof" json:"publicKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeKeyRequest) Reset() {
	*x = RecipeKeyRequest{}
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeKeyRequest) ProtoMessage() {}

func (x *RecipeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeKeyRequest.ProtoReflect.Descriptor instead.
func (*RecipeKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{0}
}

func (x *RecipeKeyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecipeKeyRequest) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *RecipeKeyRequest) GetUserAvatar() string {
	if x != nil && x.UserAvatar != nil {
		return *x.UserAvatar
	}
	return ""
}

func (x *RecipeKeyRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecipeKeyRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type GetRecipeKeyRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeKeyRequestsRequest) Reset() {
	*x = GetRecipeKeyRequestsRequest{}
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeKeyRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyRequestsRequest) ProtoMessage() {}

func (x *GetRecipeKeyRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyRequestsRequest) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecipeKeyRequestsRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *GetRecipeKeyRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetRecipeKeyRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*RecipeKeyRequest    `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeKeyRequestsResponse) Reset() {
	*x = GetRecipeKeyRequestsResponse{}
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeKeyRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeKeyRequestsResponse) ProtoMessage() {}

func (x *GetRecipeKeyRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_get_recipe_key_requests_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeKeyRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetRecipeKeyRequestsResponse) Descriptor() ([]byte, []int) {
	return file_v1_get_recipe_key_requests_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecipeKeyRequestsResponse) GetRequests() []*RecipeKeyRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_v1_get_recipe_key_requests_proto protoreflect.FileDescriptor

const file_v1_get_recipe_key_requests_proto_rawDesc = "" +
	"\n" +
	" v1/get-recipe-key-requests.proto\x12\x02v1\"\xd5\x01\n" +
	"\x10RecipeKeyRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\buserName\x18\x02 \x01(\tH\x00R\buserName\x88\x01\x01\x12#\n" +
	"\n" +
	"userAvatar\x18\x03 \x01(\tH\x01R\n" +
	"userAvatar\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\tpublicKey\x18\x05 \x01(\fH\x02R\tpublicKey\x88\x01\x01B\v\n" +
	"\t_userNameB\r\n" +
	"\v_userAvatarB\f\n" +
	"\n" +
	"_publicKey\"Q\n" +
	"\x1bGetRecipeKeyRequestsRequest\x12\x1a\n" +
	"\brecipeId\x18\x01 \x01(\tR\brecipeId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x1cGetRecipeKeyRequestsResponse\x120\n" +
	"\brequests\x18\x01 \x03(\v2\x14.v1.RecipeKeyRequestR\brequestsBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_get_recipe_key_requests_proto_rawDescOnce sync.Once
	file_v1_get_recipe_key_requests_proto_rawDescData []byte
)

func file_v1_get_recipe_key_requests_proto_rawDescGZIP() []byte {
	file_v1_get_recipe_key_requests_proto_rawDescOnce.Do(func() {
		file_v1_get_recipe_key_requests_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_get_recipe_key_requests_proto_rawDesc), len(file_v1_get_recipe_key_requests_proto_rawDesc)))
	})
	return file_v1_get_recipe_key_requests_proto_rawDescData
}

var file_v1_get_recipe_key_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_v1_get_recipe_key_requests_proto_goTypes = []any{
	(*RecipeKeyRequest)(nil),             // 0: v1.RecipeKeyRequest
	(*GetRecipeKeyRequestsRequest)(nil),  // 1: v1.GetRecipeKeyRequestsRequest
	(*GetRecipeKeyRequestsResponse)(nil), // 2: v1.GetRecipeKeyRequestsResponse
}
var file_v1_get_recipe_key_requests_proto_depIdxs = []int32{
	0, // 0: v1.GetRecipeKeyRequestsResponse.requests:type_name -> v1.RecipeKeyRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_get_recipe_key_requests_proto_init() }
func file_v1_get_recipe_key_requests_proto_init() {
	if File_v1_get_recipe_key_requests_proto != nil {
		return
	}
	file_v1_get_recipe_key_requests_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_get_recipe_key_requests_proto_rawDesc), len(file_v1_get_recipe_key_requests_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_get_recipe_key_requests_proto_goTypes,
		DependencyIndexes: file_v1_get_recipe_key_requests_proto_depIdxs,
		MessageInfos:      file_v1_get_recipe_key_requests_proto_msgTypes,
	}.Build()
	File_v1_get_recipe_key_requests_proto = out.File
	file_v1_get_recipe_key_requests_proto_goTypes = nil
	file_v1_get_recipe_key_requests_proto_depIdxs = nil
}
