// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/has-encrypted-vault.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HasEncryptedVaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasEncryptedVaultRequest) Reset() {
	*x = HasEncryptedVaultRequest{}
	mi := &file_v1_has_encrypted_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasEncryptedVaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasEncryptedVaultRequest) ProtoMessage() {}

func (x *HasEncryptedVaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_has_encrypted_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasEncryptedVaultRequest.ProtoReflect.Descriptor instead.
func (*HasEncryptedVaultRequest) Descriptor() ([]byte, []int) {
	return file_v1_has_encrypted_vault_proto_rawDescGZIP(), []int{0}
}

func (x *HasEncryptedVaultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HasEncryptedVaultResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HasEncryptedVault bool                   `protobuf:"varint,1,opt,name=hasEncryptedVault,proto3" json:"hasEncryptedVault,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HasEncryptedVaultResponse) Reset() {
	*x = HasEncryptedVaultResponse{}
	mi := &file_v1_has_encrypted_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasEncryptedVaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasEncryptedVaultResponse) ProtoMessage() {}

func (x *HasEncryptedVaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_has_encrypted_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasEncryptedVaultResponse.ProtoReflect.Descriptor instead.
func (*HasEncryptedVaultResponse) Descriptor() ([]byte, []int) {
	return file_v1_has_encrypted_vault_proto_rawDescGZIP(), []int{1}
}

func (x *HasEncryptedVaultResponse) GetHasEncryptedVault() bool {
	if x != nil {
		return x.HasEncryptedVault
	}
	return false
}

var File_v1_has_encrypted_vault_proto protoreflect.FileDescriptor

const file_v1_has_encrypted_vault_proto_rawDesc = "" +
	"\n" +
	"\x1cv1/has-encrypted-vault.proto\x12\x02v1\"2\n" +
	"\x18HasEncryptedVaultRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x19HasEncryptedVaultResponse\x12,\n" +
	"\x11hasEncryptedVault\x18\x01 \x01(\bR\x11hasEncryptedVaultBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_has_encrypted_vault_proto_rawDescOnce sync.Once
	file_v1_has_encrypted_vault_proto_rawDescData []byte
)

func file_v1_has_encrypted_vault_proto_rawDescGZIP() []byte {
	file_v1_has_encrypted_vault_proto_rawDescOnce.Do(func() {
		file_v1_has_encrypted_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_has_encrypted_vault_proto_rawDesc), len(file_v1_has_encrypted_vault_proto_rawDesc)))
	})
	return file_v1_has_encrypted_vault_proto_rawDescData
}

var file_v1_has_encrypted_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_has_encrypted_vault_proto_goTypes = []any{
	(*HasEncryptedVaultRequest)(nil),  // 0: v1.HasEncryptedVaultRequest
	(*HasEncryptedVaultResponse)(nil), // 1: v1.HasEncryptedVaultResponse
}
var file_v1_has_encrypted_vault_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_has_encrypted_vault_proto_init() }
func file_v1_has_encrypted_vault_proto_init() {
	if File_v1_has_encrypted_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_has_encrypted_vault_proto_rawDesc), len(file_v1_has_encrypted_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_has_encrypted_vault_proto_goTypes,
		DependencyIndexes: file_v1_has_encrypted_vault_proto_depIdxs,
		MessageInfos:      file_v1_has_encrypted_vault_proto_msgTypes,
	}.Build()
	File_v1_has_encrypted_vault_proto = out.File
	file_v1_has_encrypted_vault_proto_goTypes = nil
	file_v1_has_encrypted_vault_proto_depIdxs = nil
}
