// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/request-recipe-key-access.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestRecipeKeyAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      string                 `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRecipeKeyAccessRequest) Reset() {
	*x = RequestRecipeKeyAccessRequest{}
	mi := &file_v1_request_recipe_key_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRecipeKeyAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRecipeKeyAccessRequest) ProtoMessage() {}

func (x *RequestRecipeKeyAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_recipe_key_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRecipeKeyAccessRequest.ProtoReflect.Descriptor instead.
func (*RequestRecipeKeyAccessRequest) Descriptor() ([]byte, []int) {
	return file_v1_request_recipe_key_access_proto_rawDescGZIP(), []int{0}
}

func (x *RequestRecipeKeyAccessRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *RequestRecipeKeyAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RequestRecipeKeyAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRecipeKeyAccessResponse) Reset() {
	*x = RequestRecipeKeyAccessResponse{}
	mi := &file_v1_request_recipe_key_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRecipeKeyAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRecipeKeyAccessResponse) ProtoMessage() {}

func (x *RequestRecipeKeyAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_request_recipe_key_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRecipeKeyAccessResponse.ProtoReflect.Descriptor instead.
func (*RequestRecipeKeyAccessResponse) Descriptor() ([]byte, []int) {
	return file_v1_request_recipe_key_access_proto_rawDescGZIP(), []int{1}
}

func (x *RequestRecipeKeyAccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_request_recipe_key_access_proto protoreflect.FileDescriptor

const file_v1_request_recipe_key_access_proto_rawDesc = "" +
	"\n" +
	"\"v1/request-recipe-key-access.proto\x12\x02v1\"S\n" +
	"\x1dRequestRecipeKeyAccessRequest\x12\x1a\n" +
	"\brecipeId\x18\x01 \x01(\tR\brecipeId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\":\n" +
	"\x1eRequestRecipeKeyAccessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_request_recipe_key_access_proto_rawDescOnce sync.Once
	file_v1_request_recipe_key_access_proto_rawDescData []byte
)

func file_v1_request_recipe_key_access_proto_rawDescGZIP() []byte {
	file_v1_request_recipe_key_access_proto_rawDescOnce.Do(func() {
		file_v1_request_recipe_key_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_request_recipe_key_access_proto_rawDesc), len(file_v1_request_recipe_key_access_proto_rawDesc)))
	})
	return file_v1_request_recipe_key_access_proto_rawDescData
}

var file_v1_request_recipe_key_access_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_request_recipe_key_access_proto_goTypes = []any{
	(*RequestRecipeKeyAccessRequest)(nil),  // 0: v1.RequestRecipeKeyAccessRequest
	(*RequestRecipeKeyAccessResponse)(nil), // 1: v1.RequestRecipeKeyAccessResponse
}
var file_v1_request_recipe_key_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_request_recipe_key_access_proto_init() }
func file_v1_request_recipe_key_access_proto_init() {
	if File_v1_request_recipe_key_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_request_recipe_key_access_proto_rawDesc), len(file_v1_request_recipe_key_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_request_recipe_key_access_proto_goTypes,
		DependencyIndexes: file_v1_request_recipe_key_access_proto_depIdxs,
		MessageInfos:      file_v1_request_recipe_key_access_proto_msgTypes,
	}.Build()
	File_v1_request_recipe_key_access_proto = out.File
	file_v1_request_recipe_key_access_proto_goTypes = nil
	file_v1_request_recipe_key_access_proto_depIdxs = nil
}
