// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: v1/set-recipe-key.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRecipeKeyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecipeId         string                 `protobuf:"bytes,1,opt,name=recipeId,proto3" json:"recipeId,omitempty"`
	UserId           *string                `protobuf:"bytes,2,opt,name=userId,proto3,oneof" json:"userId,omitempty"`
	RequesterId      string                 `protobuf:"bytes,3,opt,name=requesterId,proto3" json:"requesterId,omitempty"`
	EncryptedKey     []byte                 `protobuf:"bytes,4,opt,name=encryptedKey,proto3" json:"encryptedKey,omitempty"`
	SubscriptionPlan string                 `protobuf:"bytes,5,opt,name=subscriptionPlan,proto3" json:"subscriptionPlan,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetRecipeKeyRequest) Reset() {
	*x = SetRecipeKeyRequest{}
	mi := &file_v1_set_recipe_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecipeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecipeKeyRequest) ProtoMessage() {}

func (x *SetRecipeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_recipe_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecipeKeyRequest.ProtoReflect.Descriptor instead.
func (*SetRecipeKeyRequest) Descriptor() ([]byte, []int) {
	return file_v1_set_recipe_key_proto_rawDescGZIP(), []int{0}
}

func (x *SetRecipeKeyRequest) GetRecipeId() string {
	if x != nil {
		return x.RecipeId
	}
	return ""
}

func (x *SetRecipeKeyRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *SetRecipeKeyRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *SetRecipeKeyRequest) GetEncryptedKey() []byte {
	if x != nil {
		return x.EncryptedKey
	}
	return nil
}

func (x *SetRecipeKeyRequest) GetSubscriptionPlan() string {
	if x != nil {
		return x.SubscriptionPlan
	}
	return ""
}

type SetRecipeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRecipeKeyResponse) Reset() {
	*x = SetRecipeKeyResponse{}
	mi := &file_v1_set_recipe_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRecipeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRecipeKeyResponse) ProtoMessage() {}

func (x *SetRecipeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_set_recipe_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRecipeKeyResponse.ProtoReflect.Descriptor instead.
func (*SetRecipeKeyResponse) Descriptor() ([]byte, []int) {
	return file_v1_set_recipe_key_proto_rawDescGZIP(), []int{1}
}

func (x *SetRecipeKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_set_recipe_key_proto protoreflect.FileDescriptor

const file_v1_set_recipe_key_proto_rawDesc = "" +
	"\n" +
	"\x17v1/set-recipe-key.proto\x12\x02v1\"\xcb\x01\n" +
	"\x13SetRecipeKeyRequest\x12\x1a\n" +
	"\brecipeId\x18\x01 \x01(\tR\brecipeId\x12\x1b\n" +
	"\x06userId\x18\x02 \x01(\tH\x00R\x06userId\x88\x01\x01\x12 \n" +
	"\vrequesterId\x18\x03 \x01(\tR\vrequesterId\x12\"\n" +
	"\fencryptedKey\x18\x04 \x01(\fR\fencryptedKey\x12*\n" +
	"\x10subscriptionPlan\x18\x05 \x01(\tR\x10subscriptionPlanB\t\n" +
	"\a_userId\"0\n" +
	"\x14SetRecipeKeyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageBAZ?github.com/mephistolie/chefbook-backend-encryption/api/proto/v1b\x06proto3"

var (
	file_v1_set_recipe_key_proto_rawDescOnce sync.Once
	file_v1_set_recipe_key_proto_rawDescData []byte
)

func file_v1_set_recipe_key_proto_rawDescGZIP() []byte {
	file_v1_set_recipe_key_proto_rawDescOnce.Do(func() {
		file_v1_set_recipe_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_set_recipe_key_proto_rawDesc), len(file_v1_set_recipe_key_proto_rawDesc)))
	})
	return file_v1_set_recipe_key_proto_rawDescData
}

var file_v1_set_recipe_key_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_set_recipe_key_proto_goTypes = []any{
	(*SetRecipeKeyRequest)(nil),  // 0: v1.SetRecipeKeyRequest
	(*SetRecipeKeyResponse)(nil), // 1: v1.SetRecipeKeyResponse
}
var file_v1_set_recipe_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_set_recipe_key_proto_init() }
func file_v1_set_recipe_key_proto_init() {
	if File_v1_set_recipe_key_proto != nil {
		return
	}
	file_v1_set_recipe_key_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_set_recipe_key_proto_rawDesc), len(file_v1_set_recipe_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_set_recipe_key_proto_goTypes,
		DependencyIndexes: file_v1_set_recipe_key_proto_depIdxs,
		MessageInfos:      file_v1_set_recipe_key_proto_msgTypes,
	}.Build()
	File_v1_set_recipe_key_proto = out.File
	file_v1_set_recipe_key_proto_goTypes = nil
	file_v1_set_recipe_key_proto_depIdxs = nil
}
